### ISSUE TITLE
Fyusenet works in OpenGL but not in GLES2 and EGL

### ISSUE THREAD

**Issue by IssacXid** [Fyusion-Open-Source/fyusenet#9]
Good Afternoon,

I’ve been working with a target board with PowerVR GPU. The target board just has OpenGLES and EGL and doesn’t have OpenGL / glx / glfw / GLUT / GLU / GLVND etc. 

I’ve been able to run the sample resnet, provided in fyusenet, successfully on a host Ubuntu system with OpenGL, glx and GLVND, but in the target board, the output of the resnet is always coming out to be the first class. I tried printing the intermediate layers to narrow down which layer is causing the issue and it came out to be the second last layer, which is defined in a file called `deepgemmlayer.cpp`. I used the enableIntermediateOutput() API in the fyusenet library and converting the binary raw intermediate feature maps to decimals. I think it has something to do with how the shader is getting executed by GLES-EGL combination. I've tried changing the precision values in the .vert and .frag shader programs assuming that the board hardware might not support all the operation required in the gemm layer, but it also ends up giving the same all zero output. Though the assumption was more on a test and try basis, as all the previous layer's feature maps are coming out to be non-zero floating points, similar to the host Ubuntu system.

Can anyone help me find out the issue why the shaders might be behaving in such a way that the layer’s output becomes all 0?

Thanks in advance for any help.

**Comment by mtnwrw** [comment]
Hi @IssacXid ,

Sorry for getting back at you so late. First of all, can you tell me what GPU and OS you are running on ? On StackOverflow I saw that you mentioned PowerVR, which model exactly ?

Also, I have a personal [fork](https://github.com/mtnwrw/fyusenet) with a bunch of updates, can you reproduce the same problem on that ?

If that problem persists we can look a bit deeper and try to figure out what's going on.

**Comment by IssacXid** [comment]
Hey @mtnwrw,

Unfortunately, I don't have access to the target board right now. It's expected to be returned to me by Monday. Once I have the board back, I'll try reproducing the issue on your fork as well and let you know the outcome.

Target board has a IMG AXM-8-256 GPU, and OS is Linux.

Thanks for your help.

**Comment by mtnwrw** [comment]
I got my hands on [this](https://doc-en.rvspace.org/VisionFive2/Product_Brief/VisionFive_2/specification_pb.html) over the weekend. 

It has the IMG BXE-4-32 MC1 GPU, which should be quite a bit slower than the one that you are using, still working on getting the GPU drivers to work properly :-)

I saw that you mentioned GLES 2.0, I would like to note that FyuseNet requires GLES 3.0 to work. Though it should be possible
to get it to work with GLES 2.0 (with some adaptions on the shaders), I would not recommend it. Given that only the point-primitive layer in the end causes problems, I assume you are running under GLES 3.0 (it would have failed way earlier otherwise).
I already have an idea what could be wrong, will test it here locally, otherwise I will provide instructions here (should be a one-line fix).

**Comment by IssacXid** [comment]
Hello,
Thanks for testing it out while I couldn't access the board. I got it running, cloned and built the modified repository with some changes:
1) Setting the flag BUILD_TESTS OFF as it results in fetching gtest repository as we cannot connect the target board to internet.
2) In CMakeLists.txt, I replaced the arguement OpenGL in find_package() with OpenGLES and EGL, for which I've added the FindOpenGLES.cmake and FindEGL.cmake in the cmake directory.
3) Changed some occurences of GLES/gl.h with GLES2/gl2.h, GLES/glext.h with GLES2/gl2ext.h and GLES3/gl3ext.h with GLES3/gl2ext.h as per the files available in the target board.
Before reaching to the point of replicating the deepgemmlayer.cpp, I'm trying to debug another error that I didn't face with the original fyusenet repository: 

```
  - GL_OVR_multiview2
terminate called after throwing an instance of 'fyusion::opengl::GLException'
  what():  /home/root/github_issue/fyusenet/fyusenet/base/buffermanager.cpp:724 [fyusion::fyusenet::BufferManager::Textn
Detailed error: Cannot parameterize texture (err=0x502)

Aborted
```
Do you know why this is occurring? I'll try to debug it in the meantime.

**Comment by mtnwrw** [comment]
Hey @IssacXid ,

So to your point 2, that is actually a good idea. Would you mind setting up a PR into my fork with the changes in CMakeLists.txt and the cmake modules ?

Point 3 puzzles me a little bit. It is possible that different Linux distros handle things differently, but debian and Ubuntu put the headers into `/usr/include/GLES`. They do however also have copies in the other folders you mentioned. Perhaps I should do some homework on which pattern is more common among different distros and settle for a common theme here.

The error (0x502) that you see there is a long standing nuisance in my codebase which has to do with GLES and the support of RGB textures (as write targets). Don't get me started on that :-)

I set up a PR [here](https://github.com/mtnwrw/fyusenet/pull/5) which fixes that issue as well as another issue that I discovered when testing on the RISC-V board.

Your initial problem (the zero output in the GEMM layer) was already fixed in my fork, it was a simple line in the vertex shaders:

```
gl_PointSize = 1.0
```
Not all drivers seem to use the default (1.0) when not explicitly instructed to.

But there was another bug that only occured on weaker GPUs, which yields wrong results in convolution layers with larger kernels. That is also addressed and fixed in the PR above.

I could run the ResNet50 sample on the RISC-V board. The performance was not overwhelming (around 1800ms), but the GPU on that board is on the low end of the spectrum for PowerVR archs. So I hope that you get a bit more performance out of it.

Also the drivers that are available for my board do not seem to be really mature. For example I was not able to get any sane results when using 16-bit FP textures, I had to set the `HIGH_PRECISION` flag in the `CMakeLists.txt` to `ON` to make it work.

Anyway, let me know if this solves your issue.

P.S.: can you post the output of the GLInfo part of your GPU (the lengthy output at the beginning when using debug builds) ?

**Comment by IssacXid** [comment]
Sure thing! 🚀 PR is up! Also, regarding `gl_PointSize = 1.0`, can you pinpoint to the exact files for that tweak? I'll try to make it work for original fyusenet if I can get the Resnet to run. 
 
 This is the GLInfo log for the target board:
```
 GL version: 3.2
GLSL version: 3.20 build 1.18@6276027
GPU vendor: Imagination Technologies
GPU renderer: PowerVR A-Series AXM-8-256
Caps:
  GL_MAX_TEXTURE_SIZE: 16384
  GL_MAX_VERTEX_ATTRIBS: 16
  GL_MAX_VERTEX_UNIFORM_VECTORS: 1024
  GL_MAX_VARYING_VECTORS: 15
  GL_MAX_VERTEX_OUTPUT_COMPONENTS: 64
  GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS: 144
  GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS: 24
  GL_MAX_TEXTURE_IMAGE_UNITS: 24
  GL_MAX_FRAGMENT_UNIFORM_VECTORS: 1024
  GL_MAX_FRAGMENT_INPUT_COMPONENTS: 60
  GL_MAX_COLOR_ATTACHMENTS: 8
  GL_MAX_DRAW_BUFFERS: 8
  GL_MAX_FRAGMENT_UNIFORM_COMPONENTS: 4096
  GL_MAX_VERTEX_UNIFORM_COMPONENTS: 4096
  (I) GL_FRAGMENT_LOW: [15 15]
  (I) GL_FRAGMENT_MEDIUM: [15 15]
  (I) GL_FRAGMENT_HIGH: [31 31]
  (F) GL_FRAGMENT_LOW: [1 1] 8
  (F) GL_FRAGMENT_MEDIUM: [14 14] 10
  (F) GL_FRAGMENT_HIGH: [127 127] 23
  GL_MAX_UNIFORM_BUFFER_BINDINGS: 72
  GL_MAX_VERTEX_UNIFORM_BLOCKS: 12
  GL_MAX_FRAGMENT_UNIFORM_BLOCKS: 12
  GL_MAX_COMBINED_UNIFORM_BLOCKS: 72
  GL_MAX_UNIFORM_BLOCK_SIZE: 134217728
  GL_UNIFORM_BUFFER_OFFSET_ALIGNMENT: 128
  GL_MIN_PROGRAM_TEXEL_OFFSET: -8
  GL_MAX_PROGRAM_TEXEL_OFFSET: 7
  GL_MAX_COMBINED_VERTEX_UNIFORM_COPONENTS: 402657280
  GL_MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS: 402657280
  GL_MAX_COMPUTE_IMAGE_UNIFORMS: 24
  GL_MAX_COMPUTE_SHADER_STORAGE_BLOCKS: 35
  GL_MAX_COMPUTE_SHADER_STORAGE_BLOCKS: 24
  GL_MAX_COMPUTE_SHADER_STORAGE_BLOCKS: 0
  GL_MAX_COMPUTE_UNIFORM_BLOCKS: 12
  GL_MAX_COMPUTE_UNIFORM_COMPONENTS: 1024
  GL_MAX_COMPUTE_WORK_GROUP_INVOCATIONS: 1024
  GL_MAX_COMPUTE_WORK_GROUP_SIZE: 1024 1024 1024
  GL_MAX_COMPUTE_WORK_GROUP_COUNT: 65535 65535 65535
GL_MAX_TEXTURE_BUFFER_SIZE: 65536
Extensions:
  - GL_ANDROID_extension_pack_es31a
  - GL_APPLE_texture_format_BGRA8888
  - GL_ARM_shader_framebuffer_fetch_depth_stencil
  - GL_EXT_blend_minmax
  - GL_EXT_buffer_storage
  - GL_EXT_clear_texture
  - GL_EXT_clip_control
  - GL_EXT_color_buffer_float
  - GL_EXT_color_buffer_half_float
  - GL_EXT_compressed_ETC1_RGB8_sub_texture
  - GL_EXT_conservative_depth
  - GL_EXT_copy_image
  - GL_EXT_discard_framebuffer
  - GL_EXT_draw_buffers
  - GL_EXT_draw_buffers_indexed
  - GL_EXT_draw_elements_base_vertex
  - GL_EXT_EGL_image_array
  - GL_EXT_float_blend
  - GL_EXT_geometry_point_size
  - GL_EXT_geometry_shader
  - GL_EXT_gpu_shader5
  - GL_EXT_memory_object
  - GL_EXT_memory_object_fd
  - GL_EXT_multi_draw_arrays
  - GL_EXT_multi_draw_indirect
  - GL_EXT_multisampled_render_to_texture
  - GL_EXT_multisampled_render_to_texture2
  - GL_EXT_occlusion_query_boolean
  - GL_EXT_polygon_offset_clamp
  - GL_EXT_primitive_bounding_box
  - GL_EXT_pvrtc_sRGB
  - GL_EXT_read_format_bgra
  - GL_EXT_robustness
  - GL_EXT_separate_shader_objects
  - GL_EXT_shader_framebuffer_fetch
  - GL_EXT_shader_group_vote
  - GL_EXT_shader_implicit_conversions
  - GL_EXT_shader_io_blocks
  - GL_EXT_shader_non_constant_global_initializers
  - GL_EXT_shader_pixel_local_storage
  - GL_EXT_shader_pixel_local_storage2
  - GL_EXT_shader_texture_lod
  - GL_EXT_shadow_samplers
  - GL_EXT_sparse_texture
  - GL_EXT_sRGB
  - GL_EXT_sRGB_write_control
  - GL_EXT_tessellation_point_size
  - GL_EXT_tessellation_shader
  - GL_EXT_texture_border_clamp
  - GL_EXT_texture_buffer
  - GL_EXT_texture_cube_map_array
  - GL_EXT_texture_filter_anisotropic
  - GL_EXT_texture_format_BGRA8888
  - GL_EXT_texture_format_sRGB_override
  - GL_EXT_texture_norm16
  - GL_EXT_texture_rg
  - GL_EXT_texture_shadow_lod
  - GL_EXT_texture_sRGB_decode
  - GL_EXT_texture_sRGB_R8
  - GL_EXT_texture_sRGB_RG8
  - GL_EXT_texture_type_2_10_10_10_REV
  - GL_EXT_unpack_subimage
  - GL_EXT_YUV_target
  - GL_EXT_texture_storage_compression
  - GL_IMG_framebuffer_downsample
  - GL_IMG_multisampled_render_to_texture
  - GL_IMG_program_binary
  - GL_IMG_read_format
  - GL_IMG_shader_binary
  - GL_IMG_texture_compression_pvrtc
  - GL_IMG_texture_compression_pvrtc2
  - GL_IMG_texture_format_BGRA8888
  - GL_IMG_texture_npot
  - GL_KHR_blend_equation_advanced
  - GL_KHR_blend_equation_advanced_coherent
  - GL_KHR_debug
  - GL_KHR_robustness
  - GL_KHR_texture_compression_astc_ldr
  - GL_OES_compressed_ETC1_RGB8_texture
  - GL_OES_depth24
  - GL_OES_depth_texture
  - GL_OES_depth_texture_cube_map
  - GL_OES_draw_buffers_indexed
  - GL_OES_draw_elements_base_vertex
  - GL_OES_EGL_image
  - GL_OES_EGL_image_external
  - GL_OES_EGL_image_external_essl3
  - GL_OES_EGL_sync
  - GL_OES_element_index_uint
  - GL_OES_fragment_precision_high
  - GL_OES_geometry_point_size
  - GL_OES_geometry_shader
  - GL_OES_get_program_binary
  - GL_OES_gpu_shader5
  - GL_OES_mapbuffer
  - GL_OES_packed_depth_stencil
  - GL_OES_required_internalformat
  - GL_OES_rgb8_rgba8
  - GL_OES_sample_shading
  - GL_OES_sample_variables
  - GL_OES_shader_image_atomic
  - GL_OES_shader_io_blocks
  - GL_OES_shader_multisample_interpolation
  - GL_OES_standard_derivatives
  - GL_OES_surfaceless_context
  - GL_OES_tessellation_point_size
  - GL_OES_tessellation_shader
  - GL_OES_texture_3D
  - GL_OES_texture_border_clamp
  - GL_OES_texture_buffer
  - GL_OES_texture_cube_map_array
  - GL_OES_texture_float
  - GL_OES_texture_half_float
  - GL_OES_texture_npot
  - GL_OES_texture_stencil8
  - GL_OES_texture_storage_multisample_2d_array
  - GL_OES_vertex_array_object
  - GL_OES_vertex_half_float
  - GL_OES_viewport_array
  - GL_OVR_multiview
  - GL_OVR_multiview2
  ```
